# Docker
# Build a Docker image 
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- master

resources:
- repo: self

variables:
  tag: '$(Build.BuildId)'

stages:
- stage: Build
  displayName: Build image
  jobs:  
  - job: Build
    displayName: Build
    pool:
      vmImage: 'ubuntu-latest'
    steps:
    - task: DockerInstaller@0
      inputs:
        dockerVersion: '17.09.0-ce'
    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        command: 'login'

    - task: Docker@2
      inputs:
        containerRegistry: 'DockerHub'
        repository: 'lethiux/pictly'
        command: 'buildAndPush'
        Dockerfile: '**/Dockerfile'
        tags: |
              $(tag)

    - task: CmdLine@2
      inputs:
        script: |
          sonar-scanner \
            -Dsonar.projectKey=pictly \
            -Dsonar.sources=. \
            -Dsonar.host.url=https://8080-06cd0fab-2ba3-45d4-accd-40d5f4cf86d8.asia-southeast1.cloudshell.dev \
            -Dsonar.login=c0609db03246dd58a5429a28ed43dace5a893188
