version: '3.7'

services:

  example:
    container_name: pictly
    image: lethiux/pictly
    volumes:
      - '.:/app'
      - '/app/node_modules'
    ports:
      - '4200:4200'
    command: >
      ng serve --host 0.0.0.0 --port 4200